tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

brew "asdf"
brew "autojump"
brew "bat"
brew "chezmoi"
brew "direnv"
brew "fish"
brew "fisher"
brew "gh"
brew "git"
brew "neovim"
brew "thefuck"
brew "tldr"
brew "tmux"
brew "vim"
brew "yqrashawn/goku/goku"

cask "1password-beta"
cask "alfred"
cask "cloudflare-warp"
cask "discord"
cask "dropbox"
cask "firefox-developer-edition"
cask "font-meslo-lg-nerd-font"
cask "insomnia"
cask "lens"
cask "postico"
cask "signal"
cask "sequel-pro-nightly"
cask "slack"
cask "steam"
cask "sublime-merge"
cask "sublime-text"
cask "telegram"
cask "visual-studio-code"
cask "protonvpn"
cask "brave-browser"
cask "kitty"
cask "docker"
cask "karabiner-elements"
cask "zerotier-one"

cask "stats"

mas "1password-for-safari"

# emacs
tap "railwaycat/emacsmacport"
cask "railwaycat/emacsmacport/emacs-mac"

