[[language]]
name = "javascript"

# [language.debugger]
# name = "node"
# command = "node"

[[language]]
name = "typescript"
auto-format = true

[[grammar]]
name = "typescript"
source = { git = "https://github.com/tree-sitter/tree-sitter-typescript.git" }

# [language.debugger]
# name = "ts-node"
# command = "ts-node"
